name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: ./pricing-table-plugin
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./pricing-table-plugin
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./pricing-table-plugin
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: /pricing-table-plugin/playwright-report/
        retention-days: 30
